"""Markdown report renderer for ssFlow OASIS-engine simulations.

Reads from `OasisSimResult` and produces a feed-first narrative organized
round-by-round:

  ## ssFlow Report — {event}
  Header with sim metadata + price summary

  Round 0 (prelude — seed event posted by market broadcaster)
  Round 1
    [publications this round, grouped by content type]
    [order flow summary with per-trader rationales]
    [price update]
  Round 2
    ...

  ## Per-class P&L
  ## Simulation Metadata

The report runs through `output_filter.assert_compliant` before display so
prescriptive vocab can never leak into the user-facing markdown.
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from .config import settings
from .information import Publication
from .output_filter import ComplianceViolation, assert_compliant, sanitize_text

if TYPE_CHECKING:
    from .oasis_engine import OasisSimResult


log = logging.getLogger(__name__)


# ─────────────────────── Currency / unit formatting ───────────────────────


CURRENCY_FORMATS: dict[str, dict[str, object]] = {
    "CNY": {"symbol": "¥",   "big_unit": "億", "big_divisor": 1e8, "small_unit": "M",  "small_divisor": 1e6},
    "USD": {"symbol": "$",   "big_unit": "B",  "big_divisor": 1e9, "small_unit": "M",  "small_divisor": 1e6},
    "EUR": {"symbol": "€",   "big_unit": "B",  "big_divisor": 1e9, "small_unit": "M",  "small_divisor": 1e6},
    "JPY": {"symbol": "¥",   "big_unit": "B",  "big_divisor": 1e9, "small_unit": "M",  "small_divisor": 1e6},
    "HKD": {"symbol": "HK$", "big_unit": "B",  "big_divisor": 1e9, "small_unit": "M",  "small_divisor": 1e6},
    "BTC": {"symbol": "₿",   "big_unit": "K",  "big_divisor": 1e3, "small_unit": "",   "small_divisor": 1.0},
}


def _fmt_price(value: float, currency: str = "CNY") -> str:
    fmt = CURRENCY_FORMATS.get(currency, CURRENCY_FORMATS["USD"])
    return f"{fmt['symbol']}{value:.2f}"


def _fmt_big(value: float, currency: str = "CNY") -> str:
    fmt = CURRENCY_FORMATS.get(currency, CURRENCY_FORMATS["USD"])
    return f"{fmt['symbol']}{value / fmt['big_divisor']:.2f}{fmt['big_unit']}"


def _fmt_small(value: float, currency: str = "CNY") -> str:
    fmt = CURRENCY_FORMATS.get(currency, CURRENCY_FORMATS["USD"])
    return f"{fmt['symbol']}{value / fmt['small_divisor']:.2f}{fmt['small_unit']}"


def _event_currency(result: "OasisSimResult") -> str:
    return getattr(result.event, "price_currency", None) or "CNY"


# ─────────────────────── Section renderers ───────────────────────


def _render_header(result: "OasisSimResult") -> str:
    event = result.event
    currency = _event_currency(result)
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    instrument = getattr(event, "instrument", None) or event.ticker
    return f"""# ssFlow Market Simulation Report

**Event**: `{instrument}` · {event.event_type} · {event.event_date}
**Simulation ID**: `{result.simulation_id}`
**Engine**: OASIS (camel-oasis) + ssFlow trading layer
**Scale**: {result.n_traders} trader archetypes + {result.n_personas - result.n_traders} info entities · ~{result.n_agents:,} simulated agents × {result.n_rounds} rounds
**Initial price**: {_fmt_price(result.initial_price, currency)} · **Final**: {_fmt_price(result.final_price, currency)}
**Cumulative**: **{result.cumulative_delta_pct * 100:+.2f}%**
**Wall clock**: {result.elapsed_seconds:.1f}s · **Cost**: ${result.cost_usd:.4f}
**Generated**: {now}

> Report generated by ssFlow (Phase I — OASIS-based information ecosystem).
> Each round, OASIS advances the social state (posts, reposts, follows) and
> the trading layer reads each trader's filtered feed to produce structured
> orders. Net order flow → Kyle square-root price impact → new price posted
> back into the OASIS feed as a `__market__` event. λ = {result.lambda_used:.2f},
> ADV = {_fmt_big(result.adv_value_used, currency)}.

---
"""


def _publication_line(pub: Publication) -> str:
    """Render one publication as a single feed line."""
    cite = ""
    if pub.references:
        cite = f" (citing {pub.references[0]})"
    body = sanitize_text(pub.text).replace("\n", " ").strip()[:280]
    return f"- **[{pub.content_type}]** {pub.author_archetype}{cite}: {body}"


def _render_round_publications(pubs: list[Publication]) -> str:
    """Group a round's publications by content type, return markdown bullets."""
    if not pubs:
        return "_(no publications this round)_"
    # Sort by content type, then by post_id
    by_type: dict[str, list[Publication]] = {}
    for pub in pubs:
        by_type.setdefault(pub.content_type, []).append(pub)
    # Stable order for content types
    type_order = [
        "company_announcement",
        "policy_statement",
        "regulatory_inquiry",
        "research_note",
        "news_brief",
        "social_post",
        "market_event",
    ]
    lines = []
    for ctype in type_order:
        if ctype in by_type:
            for pub in by_type[ctype]:
                lines.append(_publication_line(pub))
    # Catch-all for unknown content types
    for ctype, items in by_type.items():
        if ctype not in type_order:
            for pub in items:
                lines.append(_publication_line(pub))
    return "\n".join(lines)


def _render_round_order_flow(result: "OasisSimResult", round_record) -> str:
    currency = _event_currency(result)
    fmt = CURRENCY_FORMATS.get(currency, CURRENCY_FORMATS["USD"])
    sym = fmt["symbol"]
    big_div = fmt["big_divisor"]
    big_unit = fmt["big_unit"]

    by_id = {p.id: p for p in result.personas}
    if not round_record.class_flows:
        return "_(no trading activity this round)_"

    sorted_classes = sorted(
        round_record.class_flows,
        key=lambda cf: abs(cf.net_flow),
        reverse=True,
    )

    lines = []
    for cf in sorted_classes:
        p = by_id.get(cf.persona_id)
        if not p:
            continue
        sign = "净买盘" if cf.net_flow > 0 else ("净卖盘" if cf.net_flow < 0 else "观望")
        rationale = sanitize_text(cf.rationale)[:160]
        # When flow was clamped to zero (direction guard), the original
        # rationale may contradict the "观望" label. Use neutral text.
        if cf.net_flow == 0.0 and rationale:
            _r_lower = rationale.lower()
            _has_sell = any(w in _r_lower for w in ("减持", "离场", "卖出", "做空", "降低敞口"))
            _has_buy = any(w in _r_lower for w in ("增持", "买入", "加仓", "进入", "入场"))
            if _has_sell or _has_buy:
                rationale = "本轮维持现有仓位不动。"
        # Source tag for TWAP plan or policy-forced orders
        source_tag = ""
        source = getattr(cf, "source", "llm")
        if source == "plan":
            source_tag = " [TWAP]"
        elif source == "policy":
            source_tag = " [POLICY]"

        lines.append(
            f"- **{p.archetype}**{source_tag} ({sign} {sym}{abs(cf.net_flow) / big_div:.2f}{big_unit}): _{rationale}_"
        )
    return "\n".join(lines)


def _render_execution_state(round_record, currency: str = "CNY") -> str:
    """Render limit-board execution diagnostics.

    Only emits content when limit_board_state != "normal" to avoid
    cluttering normal rounds.
    """
    state = getattr(round_record, "limit_board_state", "normal")
    if state == "normal":
        return ""

    fmt = CURRENCY_FORMATS.get(currency, CURRENCY_FORMATS["USD"])
    sym = fmt["symbol"]
    big_div = fmt["big_divisor"]
    big_unit = fmt["big_unit"]

    unfilled = getattr(round_record, "limit_board_unfilled", 0.0)
    seal = getattr(round_record, "limit_board_seal", 0.0)
    avg_fill = getattr(round_record, "avg_fill_rate", 1.0)
    total_unfilled = getattr(round_record, "total_unfilled_volume", 0.0)
    total_t1 = getattr(round_record, "total_t1_blocked", 0)

    # Count unfilled orders (class_flows with fill_rate < 1.0)
    n_unfilled_orders = 0
    if hasattr(round_record, "class_flows") and round_record.class_flows:
        n_unfilled_orders = sum(
            1 for cf in round_record.class_flows
            if getattr(cf, "fill_rate", 1.0) < 1.0
        )

    state_label = state.upper().replace("_", " ")

    lines = [
        f"\n### 执行状态 / Execution State",
        f"- 涨跌停状态: **{state_label}**",
        f"- 封单量: {sym}{unfilled / big_div:.2f}{big_unit} (封单强度: {seal:.2f})",
        f"- 平均成交率: {avg_fill * 100:.0f}% ({n_unfilled_orders}笔订单未成交)",
    ]
    if total_t1 > 0:
        lines.append(f"- T+1锁定: {total_t1}笔卖单被限制")

    return "\n".join(lines) + "\n"


def _render_phase_breakdown(round_record, currency: str = "CNY") -> str:
    """Render phase-level breakdown (fast_react / slow_react) if available."""
    phase_results = getattr(round_record, "phase_results", None)
    if not phase_results:
        return ""
    fmt = CURRENCY_FORMATS.get(currency, CURRENCY_FORMATS["USD"])
    sym = fmt["symbol"]
    big_div = fmt["big_divisor"]
    big_unit = fmt["big_unit"]
    lines = ["\n### Phase breakdown"]
    for pr in phase_results:
        if isinstance(pr, dict):
            phase_name = pr.get("phase", "?")
            pb = pr.get("price_before", 0)
            pa = pr.get("price_after", 0)
            dp = pr.get("delta_pct", 0)
            nf = pr.get("net_flow", 0)
            na = pr.get("n_active_personas", 0)
            np_ = pr.get("n_plan_executions", 0)
        else:
            phase_name = pr.phase if isinstance(pr.phase, str) else pr.phase.value
            pb, pa, dp = pr.price_before, pr.price_after, pr.delta_pct
            nf = pr.net_flow
            na = pr.n_active_personas
            np_ = pr.n_plan_executions
        lines.append(
            f"- **{phase_name}**: "
            f"{sym}{pb:.2f} → {sym}{pa:.2f} ({dp*100:+.2f}%), "
            f"flow={sym}{nf/big_div:+.2f}{big_unit}"
        )
    return "\n".join(lines) + "\n"


def _render_round_block(result: "OasisSimResult", round_record) -> str:
    currency = _event_currency(result)
    sym = CURRENCY_FORMATS.get(currency, CURRENCY_FORMATS["USD"])["symbol"]

    pub_section = _render_round_publications(round_record.publications_this_round)
    flow_section = _render_round_order_flow(result, round_record)
    exec_section = _render_execution_state(round_record, currency)
    phase_section = _render_phase_breakdown(round_record, currency)

    delta_pct_str = f"{round_record.delta_pct * 100:+.2f}%"
    external_marker = ""
    if round_record.external_events_injected > 0:
        external_marker = (
            f" — **{round_record.external_events_injected} external event(s) injected**"
        )

    # Round character badge
    round_char = getattr(round_record, "round_character", "")
    char_badge = ""
    if round_char == "quiet":
        char_badge = " — **安静轮** (多数参与者未行动)"
    elif round_char == "plan_only":
        plan_n = getattr(round_record, "plan_executions", 0)
        char_badge = f" — **计划执行轮** ({plan_n} TWAP slices)"

    return f"""## Round {round_record.round_idx}{external_marker}{char_badge}
{sym}{round_record.price_before:.2f} → {sym}{round_record.price_after:.2f} ({delta_pct_str})
{phase_section}
### Publications this round
{pub_section}

### Order flow
{flow_section}
{exec_section}
---
"""


def _render_class_pnl_table(result: "OasisSimResult") -> str:
    currency = _event_currency(result)
    fmt = CURRENCY_FORMATS.get(currency, CURRENCY_FORMATS["USD"])
    sym = fmt["symbol"]
    sm_div = fmt["small_divisor"]
    sm_unit = fmt["small_unit"]

    by_id = {p.id: p for p in result.personas}
    pnl = result.compute_class_pnl()
    if not pnl:
        return "_(no agents)_"

    # Compute active vs passive P&L decomposition
    active_pnl = result.compute_class_active_pnl()
    passive_pnl = result.compute_class_passive_pnl()

    # ── Table 1: Active Trading P&L (sorted by active P&L) ──
    active_rows = sorted(active_pnl.items(), key=lambda kv: kv[1], reverse=True)
    lines = [
        f"### Active Trading P&L (from decisions made during simulation)\n",
        f"| Persona class | Archetype | Trading P&L ({sym}{sm_unit}) | Per-agent ({sym}k) | Agents |",
        "|---|---|---|---|---|",
    ]
    for cid, a_pnl in active_rows:
        p = by_id.get(cid)
        if p is None or p.sandbox is None:
            continue
        n_agents = p.sandbox.instance_count
        per_agent = (a_pnl / n_agents / 1e3) if n_agents else 0.0
        lines.append(
            f"| `{cid}` | {p.archetype} | "
            f"{a_pnl / sm_div:+.2f} | {per_agent:+.1f} | {n_agents} |"
        )

    # ── Table 2: Passive Position Float (top 5 by magnitude) ──
    passive_rows = sorted(passive_pnl.items(), key=lambda kv: abs(kv[1]), reverse=True)
    lines.append(f"\n### Passive Position Float (unrealized gain on pre-existing holdings)\n")
    lines.append(f"| Persona class | Archetype | Float ({sym}{sm_unit}) | Agents |")
    lines.append("|---|---|---|---|")
    for cid, p_pnl in passive_rows[:5]:
        p = by_id.get(cid)
        if p is None or p.sandbox is None:
            continue
        n_agents = p.sandbox.instance_count
        lines.append(
            f"| `{cid}` | {p.archetype} | "
            f"{p_pnl / sm_div:+.2f} | {n_agents} |"
        )

    return "\n".join(lines)


def _render_metadata(result: "OasisSimResult") -> str:
    event = result.event
    currency = _event_currency(result)
    return f"""## Simulation Metadata

- Event text hash: `{event.text_hash}`
- Context completeness: {event.context_completeness:.0%}
- Engine: **OASIS** (camel-oasis, Phase I)
- λ used: {result.lambda_used:.3f}
- ADV used: {_fmt_big(result.adv_value_used, currency)}
- Price range (across rounds): {_fmt_price(min(result.price_trajectory), currency)} – {_fmt_price(max(result.price_trajectory), currency)}
- LLM seed: {result.llm_seed}
- Total publications: {len(result.all_publications)} across {result.n_rounds} rounds
- OASIS db: `{result.oasis_db_path}`

_Note: This output is the result of {result.n_personas} real-data-calibrated
participant classes (traders + media + analysts + regulators + KOLs)
simulating their reactions to the event through a social information ecosystem.
The price is NOT a prediction; it is a simulated market reaction. Treat this
as a thought experiment of "what if real-distribution market participants
talked to each other and reacted to this event" — not as investment advice._
"""


def _render_multi_instrument_table(result: "OasisSimResult") -> str:
    """Render a per-instrument price summary table when multi-instrument data exists."""
    if not result.price_trajectories or len(result.price_trajectories) <= 1:
        return ""

    currency = _event_currency(result)
    fmt = CURRENCY_FORMATS.get(currency, CURRENCY_FORMATS["USD"])
    sym = fmt["symbol"]

    lines = [
        "## Multi-Instrument Price Summary\n",
        f"| Instrument | Initial | Final | Change | High | Low |",
        "|---|---|---|---|---|---|",
    ]
    for ticker, traj in result.price_trajectories.items():
        if not traj:
            continue
        initial = traj[0]
        final = traj[-1]
        if initial > 0:
            delta = (final / initial - 1.0) * 100
            delta_str = f"{delta:+.2f}%"
        else:
            delta_str = "—"
        high = max(traj)
        low = min(traj)
        lines.append(
            f"| `{ticker}` | {sym}{initial:.2f} | {sym}{final:.2f} | "
            f"**{delta_str}** | {sym}{high:.2f} | {sym}{low:.2f} |"
        )

    return "\n".join(lines)


def render_simulation_markdown(result: "OasisSimResult") -> str:
    """Compose the full markdown report for a Phase I OASIS simulation."""
    parts = [_render_header(result)]
    for round_record in result.rounds:
        parts.append(_render_round_block(result, round_record))

    # Multi-instrument summary (only rendered when >1 instrument tracked)
    multi_table = _render_multi_instrument_table(result)
    if multi_table:
        parts.append(multi_table)
        parts.append("\n---\n")

    parts.append("## Per-class P&L\n")
    parts.append(_render_class_pnl_table(result))
    parts.append("\n\n---\n")
    parts.append(_render_metadata(result))
    return "\n".join(parts).strip()


# Backward-compat alias used by tests + run_one.py
render_sandbox_markdown = render_simulation_markdown


def render_simulation_safe_or_quarantine(result: "OasisSimResult") -> tuple[str, bool]:
    """Render the simulation markdown and run it through the compliance filter.

    On violation, write the raw report to a quarantine path and return a
    placeholder for the user-facing display.
    """
    full_md = render_simulation_markdown(result)
    try:
        assert_compliant(full_md)
        return full_md, True
    except ComplianceViolation as exc:
        quarantine_dir = Path(settings.project_root) / "reports" / "quarantine"
        quarantine_dir.mkdir(parents=True, exist_ok=True)
        path = quarantine_dir / f"{result.simulation_id}.md"
        path.write_text(full_md, encoding="utf-8")
        log.warning(
            "Simulation report %s quarantined. Violations: %s. Saved to %s",
            result.simulation_id, exc.violations, path,
        )
        placeholder = (
            f"# ssFlow Simulation Report - Verification in progress\n\n"
            f"Simulation ID: `{result.simulation_id}`\n\n"
            f"The output is undergoing compliance verification.\n"
            f"Developers: see `reports/quarantine/{result.simulation_id}.md`.\n"
        )
        return placeholder, False


# Backward-compat alias used by tests + run_one.py
render_sandbox_safe_or_quarantine = render_simulation_safe_or_quarantine


def save_report(text: str, simulation_id: str) -> Path:
    """Persist a report to the reports/ dir, return its path."""
    reports_dir = settings.reports_dir
    path = reports_dir / f"{simulation_id}.md"
    path.write_text(text, encoding="utf-8")
    return path


__all__ = [
    "CURRENCY_FORMATS",
    "render_simulation_markdown",
    "render_simulation_safe_or_quarantine",
    "render_sandbox_markdown",  # backward-compat
    "render_sandbox_safe_or_quarantine",  # backward-compat
    "save_report",
]
