// Lightweight reactive session store. Persists the auth password to
// localStorage so the user only enters it once. Holds the in-flight
// session_id, the EventProposal returned by /extract, and the persona
// partials the user is editing in SetupView.

import { reactive, watch } from 'vue'

const LS_PASSWORD_KEY = 'ssflow.password'
const LS_SESSION_KEY = 'ssflow.session'
const LS_LAST_SIM_KEY = 'ssflow.lastSim'
const LS_UNIVERSE_KEY = 'ssflow.instrumentUniverse'
const LS_SCHEDULE_KEY = 'ssflow.roundSchedule'

const initial = {
  password: localStorage.getItem(LS_PASSWORD_KEY) || '',
  sessionId: '',
  uploadedFiles: [],     // [{tmp_path, name, size, kind}]
  prompt: '',
  urls: [],              // string[]
  eventProposal: null,   // dict or null
  personasProposed: [],  // partial dicts
  basePersonasPath: 'personas/ashare.yaml',
  ingestedDocs: [],
  // IDs we remember so the workflow rail can navigate to the right
  // route when the user clicks a past step.
  activeStreamId: '',          // set when /simulate-stream/init succeeds
  lastSimulationId: localStorage.getItem(LS_LAST_SIM_KEY) || '',
  lastError: '',
  // Entity State Sandbox
  entityGraph: null,           // serialized EntityGraph from /sandbox/generate or build_from_template
  entityStates: {},            // live state updates during sim, keyed by entity_id
  // Per-persona self_model state (separate namespace from entityStates
  // so the two visualisations never collide). Keyed by persona_id,
  // populated from persona_state_updated events. See
  // src/ssflow/self_model/ for the backend subsystem.
  personaStates: {},
  // Multi-instrument universe (persisted to localStorage for Replay access)
  instrumentUniverse: null,
  roundSchedule: null,
  // Per-simulation calibration parameters generated by generate_sim_params()
  // at /simulate-stream/init time. Displayed read-only in SetupView context.
  simParams: null,
}

// Restore prior session_id
try {
  const stored = JSON.parse(localStorage.getItem(LS_SESSION_KEY) || 'null')
  if (stored && stored.sessionId) initial.sessionId = stored.sessionId
} catch (_) { /* ignore */ }

// Restore instrument universe + round schedule
try {
  const iu = JSON.parse(localStorage.getItem(LS_UNIVERSE_KEY) || 'null')
  if (iu) initial.instrumentUniverse = iu
} catch (_) { /* ignore */ }
try {
  const rs = JSON.parse(localStorage.getItem(LS_SCHEDULE_KEY) || 'null')
  if (rs) initial.roundSchedule = rs
} catch (_) { /* ignore */ }

export const session = reactive(initial)

watch(() => session.password, (val) => {
  if (val) localStorage.setItem(LS_PASSWORD_KEY, val)
  else localStorage.removeItem(LS_PASSWORD_KEY)
})

watch(() => session.sessionId, (val) => {
  if (val) {
    localStorage.setItem(LS_SESSION_KEY, JSON.stringify({ sessionId: val }))
  }
})

watch(() => session.lastSimulationId, (val) => {
  if (val) localStorage.setItem(LS_LAST_SIM_KEY, val)
  else localStorage.removeItem(LS_LAST_SIM_KEY)
})

watch(() => session.instrumentUniverse, (val) => {
  if (val) localStorage.setItem(LS_UNIVERSE_KEY, JSON.stringify(val))
  else localStorage.removeItem(LS_UNIVERSE_KEY)
}, { deep: true })

watch(() => session.roundSchedule, (val) => {
  if (val) localStorage.setItem(LS_SCHEDULE_KEY, JSON.stringify(val))
  else localStorage.removeItem(LS_SCHEDULE_KEY)
}, { deep: true })

export function resetSession () {
  session.sessionId = ''
  session.uploadedFiles = []
  session.prompt = ''
  session.urls = []
  session.eventProposal = null
  session.personasProposed = []
  session.basePersonasPath = 'personas/ashare.yaml'
  session.ingestedDocs = []
  session.activeStreamId = ''
  session.lastSimulationId = ''
  session.lastError = ''
  session.entityGraph = null
  session.entityStates = {}
  session.personaStates = {}
  session.instrumentUniverse = null
  session.roundSchedule = null
}
