"""Per-persona self-model subsystem.

Gives every trader persona (static YAML or dynamically generated by
``persona_factory``) a structured **self** that the engine updates every
round, computes a utility score against, and renders into the agent's
prompt alongside the existing conviction context.

The subsystem is built as a **Library + Composition** — stable Python
primitives (atoms / utility components / render sections) that any persona
can be assembled from via a JSON spec. No per-archetype Python code. The
LLM in ``persona_factory`` Stage 3 produces the composition; the engine
runtime executes it generically.

Core exports:

- ``SelfModelSpec``    — dataclass describing one persona's self-model
- ``DEFAULT_SELF_MODEL`` — fallback bundle applied to personas without a spec
- ``StateAtomDef``     — one unit of state + update rule
- ``STATE_ATOMS``      — the full atom library (dict[name → StateAtomDef])
- ``UTILITY_COMPONENTS`` — the utility scoring functions
- ``RENDER_SECTIONS``  — the prompt render template library
- ``SelfModelEvaluator`` — runtime instance per persona
- ``build_evaluators_for_personas`` — factory helper for the engine
- ``validate_self_model_spec`` — schema guardrail for LLM-generated specs

Context: designed in response to the 2026-04-11 root-cause analysis of the
5-event monthly backtest where all personas behaved identically under
bearish doom-loop because they had no structured self-state, no utility
function, and no peer visibility. See ``analysis/backtest_monthly_v2_full.md``
for the diagnosis and the ``valiant-drifting-hippo`` plan file for the
design.
"""

from __future__ import annotations

from .schema import (
    SelfModelSpec,
    StateAtomDef,
    RoundCtx,
    TradeResult,
    validate_self_model_spec,
)
from .atoms import STATE_ATOMS
from .utility import UTILITY_COMPONENTS
from .render import RENDER_SECTIONS
from .default_bundle import DEFAULT_SELF_MODEL, DEFAULT_SELF_MODEL_DICT
from .runtime import (
    SelfModelEvaluator,
    build_evaluators_for_personas,
)


__all__ = [
    "SelfModelSpec",
    "StateAtomDef",
    "RoundCtx",
    "TradeResult",
    "validate_self_model_spec",
    "STATE_ATOMS",
    "UTILITY_COMPONENTS",
    "RENDER_SECTIONS",
    "DEFAULT_SELF_MODEL",
    "DEFAULT_SELF_MODEL_DICT",
    "SelfModelEvaluator",
    "build_evaluators_for_personas",
]
