"""External event schedule for the Phase I OASIS engine.

An `ExternalEvent` is a piece of content injected into the simulation at a
specific round, AS IF a real-world event happened during the sim. Examples:

  - Round 3: 发改委 announces a tax-credit policy
  - Round 4: a foreign supply-chain disruption hits the news
  - Round 5: a regulator opens an inquiry

These are NOT generated by LLM agents during the sim — they're scheduled
ahead of time by the operator (CLI / API caller). The `oasis_engine`
inspects the schedule at the start of each round and injects matching events
as `ManualAction(CREATE_POST)` calls on synthetic event-source agents (or on
the `__market__` agent if no specific source is configured).

This is what enables the "R3 policy surprise" pattern in the illustrative BYD
target — a planned event injected mid-sim to see how the existing agents react
to it as it propagates through the feed.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class ExternalEvent:
    """One scheduled external event to inject at a specific round.

    Attributes:
        round_idx: zero-indexed round at which the event fires (0 = first round)
        content_type: one of `ssfish.persona.VALID_CONTENT_TYPES`
        author_persona_id: which agent posts this event. Use `"__market__"`
            for events the synthetic market broadcaster sends; use a specific
            persona id (e.g., `"policy_maker_ndrc"`) to attribute it to a
            real persona in the pack.
        text: the event content as a single sentence (will be sanitized
            through `output_filter.sanitize_text` by the engine before
            being posted into OASIS).
        authority_weight: 0.0-1.0, defaults to 0.85 (external events are
            usually high-authority — analysts cite them, retail follows them).
        topic_tags: optional list of topic strings for downstream interest
            matching. Phase I doesn't use these for ranking yet.
    """

    round_idx: int
    content_type: str
    author_persona_id: str
    text: str
    authority_weight: float = 0.85
    topic_tags: list[str] = field(default_factory=list)


class ExternalEventSchedule:
    """A list of `ExternalEvent` keyed by round.

    The engine queries `events_for_round(round_idx)` at the start of each
    round and injects the matching events.
    """

    def __init__(self) -> None:
        self.events: list[ExternalEvent] = []

    def add(self, event: ExternalEvent) -> None:
        self.events.append(event)

    def events_for_round(self, round_idx: int) -> list[ExternalEvent]:
        return [e for e in self.events if e.round_idx == round_idx]

    def __len__(self) -> int:
        return len(self.events)

    def __bool__(self) -> bool:
        return bool(self.events)


__all__ = [
    "ExternalEvent",
    "ExternalEventSchedule",
]
